### ISSUE TITLE
[Iron] - Wrench - Accept NaN Values not working

### ISSUE THREAD

**Issue by firesurfer** [ros2/rviz#1139]
Hi, 

I have the issue that the `Accept NaN Values` button in rviz2 is not working. 

## Info

rviz2: 12.4.5
Ros2 distro: iron
Install: from binary

![image_480](https://github.com/ros2/rviz/assets/8481806/065aa07d-1565-49b4-b9c8-9d74c41ae42a)
The image shows that `Accept NaN Values` is ticked. But the Wrench Visualization plugin still complains. 
And no arrow is shown!

Excerpt from the message:

```
---
header:
  stamp:
    sec: 1707991810
    nanosec: 544957650
  frame_id: wire_storageB/wire_fixation_target
wrench:
  force:
    x: .nan
    y: .nan
    z: -12.128999710083008
  torque:
    x: .nan
    y: .nan
    z: .nan
---
```
